CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Orders" (
    "Id" text NOT NULL,
    "Customer" text NOT NULL,
    "Phone" text NOT NULL,
    "Address" text NOT NULL,
    "OrderPrice" numeric NOT NULL,
    "Priority" boolean NOT NULL,
    "PriorityPrice" numeric NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "EstimatedDelivery" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id")
);

CREATE TABLE "Pizzas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(20) NOT NULL,
    "UnitPrice" integer NOT NULL,
    "Ingredients" text[] NOT NULL,
    "SoldOut" boolean NOT NULL,
    "ImageUrl" text NOT NULL,
    CONSTRAINT "PK_Pizzas" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250910104829_Initial', '9.0.8');

COMMIT;

